### ISSUE TITLE
query returns weird result for non existing elements

### ISSUE THREAD

**Issue by hstaudacher** [ui4j/ui4j#32]
Querying the document with non existing elements should return`null` looking at the SelectorEngine implementations. But instead they do return an element that simply not exists.

I have no option to find out if these elements do exist or not. The `isEmpty` method of WebKitElement also is no option because it always returns `false`.

**Comment by hstaudacher** [comment]
A workaround is to queryAll and check for empty

**Comment by ui4j** [comment]
Yes, `W3CSelectorEngine.query` return `null` but Ui4j intercepts all public methods of `WebkitElement`. If selector engine return value is `null` instead of `null` value an empty WebkitElement produced by `WebKitEmptyElementProxy` and [isEmpty#L48](https://github.com/ui4j/ui4j/blob/master/ui4j-webkit/src/main/java/com/ui4j/webkit/proxy/WebKitEmptyElementProxy.java#L48) method of proxy return `true` instead of `false`. I am going to document these kind of magical things with JavaDoc after 2.0 release.

Here is sample code to test isEmpty method:

```java
package com.ui4j.test;

import com.ui4j.api.browser.BrowserEngine;
import com.ui4j.api.browser.BrowserFactory;
import com.ui4j.api.browser.Page;

public class IsEmptySample {

	public static void main(String[] args) {
		BrowserEngine webKit = BrowserFactory.getWebKit();
		Page page = webKit.navigate("about:blank");

		page.getDocument().getBody().setInnerHTML("<div id='valid-id'>my content</div>");

		System.out.println(page.getDocument().query("#valid-id").isEmpty()); // print false
		System.out.println(page.getDocument().query("#invalid-id").isEmpty()); // print true
	}
}
```

**Comment by ui4j** [comment]
The empty element logic influenced by JQuery. JQuery doesnt return null or throw any exception if the query result is empty.

**Comment by hstaudacher** [comment]
ok. So, the solution is to always check `isEmpty()`. I'm fine with it but it's not very convenient to use. You have already changed API with 2.0. So, what about let query return an Java 8 `Optional`?

**Comment by ui4j** [comment]
Although ui4j-webkit requires Java 8, ui4j-api is compatible with Java 7. Because of this requirement i didnt use Optional feature. But, Its better to drop Java 7 compatibility and use Optional feature.

**Comment by ui4j** [comment]
Element.isEmpty method removed and SelectorEngine.query() method returns Optional<Element> instead of Element.
